### PR TITLE
pip package for sensenet

### PR DESCRIPTION
**Pull request by kiryteo**
This remains to be uploaded on pypi.org

### CODE REVIEW

**Comment by jtoy** [comment]
can you commit the code that generates the package instead of the package? What command did you use to generate the package?

**Comment by kiryteo** [comment]
It required some changes with respect to setup.py, creating setup.cfg and further commands for packaging. I'll post the 'Making pip installable' text file here stating the commands required.

**Comment by kiryteo** [comment]
I have added the file mentioning all the steps taken in the process.

**Comment by jtoy** [comment]
I ran almost the  sam instructions, but they dont work because the package is always missing this folder: https://github.com/jtoy/sensenet/tree/master/sensenet/envs/handroid/data

**Comment by kiryteo** [comment]
Did you try uploading the package I created on PyPI.? Does it give the same errors.?

**Comment by jtoy** [comment]
not yet because the modified build script is not included in the pull
request, i want to rebuild it from scratch with your new code.

**Comment by kiryteo** [comment]
should I add the modified setup.py specifically.?

**Comment by jtoy** [comment]
yes please. Also I want to remove these 2 binaries from the pull request, we only need the source code, thank you!

**Comment by jtoy** [comment]
ill close this one for now, and we can just submit a new pull request with just the new setup.py

**Comment by kiryteo** [comment]
I'll add that asap.!

**Comment by kiryteo** [comment]
All right.

**Pull request closed without merging**
