### PR TITLE
setup.py for pip install

### PR DESCRIPTION
**Pull request by kiryteo**

### CODE REVIEW

**Comment by kiryteo** [comment]
@jtoy  Any update regarding this.?

**Comment by jtoy** [comment]
yes, I couldnt get your version to work building from source. I just modified the MANIFEST.in and added this to setup:
      include_package_data=True,
and it works now.

**Comment by kiryteo** [comment]
All right.! closing this.

**Comment by jtoy** [comment]
Would love help on any of the other tickets!

**Pull request closed without merging**
